"""
ml_feedback_service.py — Phase 0

Standalone event/feedback logging for the ML roadmap. This is a NEW file —
nothing in the existing `monitoring_service.py` (which logs query
latency/source for the ops dashboard) is touched or reused for this; that
file's behavior is completely unmodified.

Two event streams, each in its own SQLite table under settings.DATA_DIR
(reusing app.core.config.settings read-only — not modifying it):

  chat_feedback           — thumbs up/down on a chat answer
  recommendation_action   — "viewed" / "clicked_apply" / "checked_eligibility"
                             / "dismissed" against a specific (profile, scheme)

This is exactly the data train_ranker_from_events.py (Phase 2, real
signal) needs — export_ranker_training_rows() turns the raw event log
into the same feature shape train_ranker_bootstrap.py already uses.

NOT WIRED IN: nothing calls this service yet. The existing chat/recommend
endpoints and pages are unmodified, so no events are actually generated by
the live app until the new endpoints in
app/api/v1/endpoints/ml_feedback.py are called — which requires either the
frontend widgets in frontend/src/components/ml/ being dropped into the
existing pages, or some other client calling them directly. See
backend/ml/README.md for the exact (currently unapplied) one-line diffs
that would activate this.
"""

from __future__ import annotations

import json
import sqlite3
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

try:
    from app.core.config import settings
    _DB_PATH = settings.DATA_DIR / "ml_events.db"
except Exception:
    # Fallback so this module can be imported/tested even without a
    # configured .env (settings.py requires GEMINI_API_KEY/PINECONE_API_KEY
    # to be set) — keeps this feature genuinely standalone.
    _DB_PATH = Path(__file__).resolve().parents[3] / "data" / "ml_events.db"


@dataclass
class RankerFeatureRow:
    age: int
    annual_income: float
    occupation: str
    gender: str
    category: str
    education: str
    land_owned_acres: float
    is_bpl: int
    is_disabled: int
    scheme_id: str
    rule_score_pct: float
    matched_count: int
    missed_count: int
    engaged: int


class MLFeedbackService:

    def __init__(self, db_path: Path = _DB_PATH):
        self.db_path = db_path
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._init_db()

    def _init_db(self):
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS chat_feedback (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    timestamp DATETIME,
                    query TEXT,
                    answer_snippet TEXT,
                    helpful BOOLEAN,
                    source TEXT,
                    language TEXT
                )
            """)
            conn.execute("""
                CREATE TABLE IF NOT EXISTS recommendation_action (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    timestamp DATETIME,
                    scheme_id TEXT,
                    action TEXT,              -- viewed | clicked_apply | checked_eligibility | dismissed
                    profile_json TEXT,        -- snapshot of the profile used for this recommendation
                    rule_score_pct REAL,
                    matched_count INTEGER,
                    missed_count INTEGER,
                    is_disqualified BOOLEAN
                )
            """)

    # ── Chat feedback ──────────────────────────────────────────────────

    def log_chat_feedback(self, query: str, answer_snippet: str, helpful: bool,
                           source: str = "", language: str = "English") -> None:
        with sqlite3.connect(self.db_path) as conn:
            conn.execute(
                "INSERT INTO chat_feedback (timestamp, query, answer_snippet, helpful, source, language) "
                "VALUES (?, ?, ?, ?, ?, ?)",
                (datetime.now(), query, answer_snippet[:500], helpful, source, language),
            )

    # ── Recommendation interaction ─────────────────────────────────────

    def log_recommendation_action(self, scheme_id: str, action: str, profile: dict,
                                   rule_score_pct: float, matched_count: int,
                                   missed_count: int, is_disqualified: bool) -> None:
        with sqlite3.connect(self.db_path) as conn:
            conn.execute(
                "INSERT INTO recommendation_action "
                "(timestamp, scheme_id, action, profile_json, rule_score_pct, matched_count, missed_count, is_disqualified) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                (datetime.now(), scheme_id, action, json.dumps(profile),
                 rule_score_pct, matched_count, missed_count, is_disqualified),
            )

    # ── Stats (for an admin view later) ────────────────────────────────

    def get_stats(self) -> dict[str, Any]:
        with sqlite3.connect(self.db_path) as conn:
            chat_total = conn.execute("SELECT COUNT(*) FROM chat_feedback").fetchone()[0]
            chat_helpful = conn.execute("SELECT COUNT(*) FROM chat_feedback WHERE helpful = 1").fetchone()[0]
            action_counts = dict(conn.execute(
                "SELECT action, COUNT(*) FROM recommendation_action GROUP BY action"
            ).fetchall())
        return {
            "chat_feedback_total": chat_total,
            "chat_feedback_helpful": chat_helpful,
            "chat_helpful_rate": round(chat_helpful / chat_total, 3) if chat_total else None,
            "recommendation_actions": action_counts,
            "total_recommendation_events": sum(action_counts.values()),
        }

    # ── Training data export (consumed by train_ranker_from_events.py) ──

    def export_ranker_training_rows(self) -> list[dict]:
        """
        Turns raw recommendation_action events into the same
        (profile features, scheme features, engaged label) row shape
        train_ranker_bootstrap.py's synthetic data already uses, so both
        scripts share identical feature engineering.

        engaged = 1 if the row's action was clicked_apply/checked_eligibility,
        0 if it was dismissed or a bare "viewed" with no follow-up.
        """
        rows: list[dict] = []
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute(
                "SELECT scheme_id, action, profile_json, rule_score_pct, matched_count, "
                "missed_count, is_disqualified FROM recommendation_action WHERE is_disqualified = 0"
            )
            for scheme_id, action, profile_json, score, matched, missed, _ in cursor.fetchall():
                profile = json.loads(profile_json)
                engaged = 1 if action in ("clicked_apply", "checked_eligibility") else 0
                rows.append({
                    "age": profile.get("age", 0),
                    "annual_income": profile.get("annual_income", 0),
                    "occupation": profile.get("occupation", "other"),
                    "gender": profile.get("gender", "other"),
                    "category": profile.get("category", "general"),
                    "education": profile.get("education", "none"),
                    "land_owned_acres": profile.get("land_owned_acres", 0),
                    "is_bpl": int(profile.get("is_bpl", False)),
                    "is_disabled": int(profile.get("is_disabled", False)),
                    "scheme_id": scheme_id,
                    "rule_score_pct": score,
                    "matched_count": matched,
                    "missed_count": missed,
                    "engaged": engaged,
                })
        return rows


# Singleton
ml_feedback_service = MLFeedbackService()
