"""
ml_outcome_predictor_service.py — Phase 3 (SYNTHETIC DEMO ONLY)

Serves the demo model from ml/train_outcome_model_DEMO.py. Every response
this returns includes the disclaimer field — callers (API consumers, UI)
must not strip it before display. See ml/PHASE3_NOTES.md.

Deliberately a SEPARATE service/model from app/services/ml_outcome_service.py
(which stores real reported outcomes, and is untouched by this file).
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

MODEL_PATH = Path(__file__).resolve().parents[1] / "models" / "outcome_model_v1_SYNTHETIC_DEMO.joblib"
MANIFEST_PATH = Path(__file__).resolve().parents[1] / "models" / "outcome_model_v1_SYNTHETIC_DEMO.manifest.json"

DISCLAIMER = (
    "SYNTHETIC DEMO — this score is generated by a model trained entirely on "
    "fabricated/simulated data, not real government approval decisions. It "
    "demonstrates the modeling technique only and must not be treated as a "
    "real prediction of approval chances."
)


class MLOutcomePredictorService:

    def __init__(self):
        self._model = None
        self._feature_columns: list[str] = []
        self._manifest: Optional[dict] = None
        self._load_error: Optional[str] = None
        self._try_load()

    def _try_load(self):
        try:
            import joblib
            if not MODEL_PATH.exists():
                self._load_error = (
                    f"No trained demo model at {MODEL_PATH}. Run: "
                    f"python ml/data/generate_outcome_bootstrap.py && python ml/train_outcome_model_DEMO.py"
                )
                return
            bundle = joblib.load(MODEL_PATH)
            self._model = bundle["model"]
            self._feature_columns = bundle["feature_columns"]
            if MANIFEST_PATH.exists():
                self._manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
            logger.info(f"Loaded SYNTHETIC DEMO outcome model from {MODEL_PATH}")
        except Exception as e:
            self._load_error = str(e)
            logger.warning(f"Could not load outcome demo model: {e}")

    @property
    def is_ready(self) -> bool:
        return self._model is not None

    def predict(self, profile: dict, scheme_result: dict) -> dict:
        """
        Returns {"synthetic_approval_likelihood": float 0-1, "disclaimer": str}
        or {"synthetic_approval_likelihood": None, "disclaimer": ..., "error": ...}
        if the model isn't loaded. ALWAYS includes the disclaimer.
        """
        if not self.is_ready:
            return {"synthetic_approval_likelihood": None, "disclaimer": DISCLAIMER, "error": self._load_error}

        import pandas as pd

        row = {
            "age": profile.get("age", 0),
            "annual_income": profile.get("annual_income", 0),
            "land_owned_acres": profile.get("land_owned_acres", 0),
            "is_bpl": int(profile.get("is_bpl", False)),
            "is_disabled": int(profile.get("is_disabled", False)),
            "rule_score_pct": scheme_result.get("rule_score_pct", 0),
            "matched_count": scheme_result.get("matched_count", 0),
            "missed_count": scheme_result.get("missed_count", 0),
        }
        for col, val in [
            ("occupation", profile.get("occupation", "other")),
            ("gender", profile.get("gender", "other")),
            ("category", profile.get("category", "general")),
            ("education", profile.get("education", "none")),
        ]:
            for feature_col in self._feature_columns:
                if feature_col == f"{col}_{val}":
                    row[feature_col] = 1

        X = pd.DataFrame([row])
        for col in self._feature_columns:
            if col not in X.columns:
                X[col] = 0
        X = X[self._feature_columns]

        proba = float(self._model.predict_proba(X)[0][1])
        return {"synthetic_approval_likelihood": round(proba, 4), "disclaimer": DISCLAIMER}

    def manifest(self) -> Optional[dict]:
        return self._manifest


# Singleton
ml_outcome_predictor_service = MLOutcomePredictorService()
